# * This changes the CI env var that 
# * was recently added
# * https://community.netlify.com/t/new-ci-true-build-configuration-treating-warnings-as-errors-because-process-env-ci-true/14434
command = "CI= npm run build"